
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form AS2_demo_mohdridhwan
     */
    public main() {
        initComponents();
        setResizable(false);
        setSize(850,570);
        setLocation(600,200);
        setTitle("                                                                      BILIK PERGERAKAN COVID19");
        setIcon();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namatxt = new javax.swing.JTextField();
        alamattxt = new javax.swing.JTextField();
        notxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        j1 = new javax.swing.JComboBox<>();
        j2 = new javax.swing.JComboBox<>();
        j3 = new javax.swing.JComboBox<>();
        tar3 = new javax.swing.JTextField();
        tar = new javax.swing.JTextField();
        tar2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("NAMA PENUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 130, 110, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NO TELEPON");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 180, 120, 20);

        namatxt.setBackground(new java.awt.Color(102, 102, 102));
        namatxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        namatxt.setForeground(new java.awt.Color(255, 255, 255));
        namatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatxtActionPerformed(evt);
            }
        });
        getContentPane().add(namatxt);
        namatxt.setBounds(250, 120, 230, 30);

        alamattxt.setBackground(new java.awt.Color(102, 102, 102));
        alamattxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        alamattxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(alamattxt);
        alamattxt.setBounds(250, 170, 230, 30);

        notxt.setBackground(new java.awt.Color(102, 102, 102));
        notxt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        notxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(notxt);
        notxt.setBounds(250, 222, 230, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SUHU BADAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 230, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TARIKH (HH/BB/TTTT)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 290, 170, 20);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 340, 110, 25);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELAMAT DATANG KEDAI HAJI MOHD RIDHWAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 30, 620, 47);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Design by E.1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 500, 166, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("*SILA GUNA PENUTUP MUKA SEBELUM MASUK PREMIS INI DAN AMALKAN PENJARAKAN SOSIAL * ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 400, 710, 17);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\Projek_bilik_pergerakan\\src\\BILIK PERGERAKAN ONLINE.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 130, 200, 210);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Daftar Online");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(630, 340, 90, 17);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Admin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 490, 110, 25);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 340, 110, 25);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 490, 110, 25);

        j1.setBackground(new java.awt.Color(102, 102, 102));
        j1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        j1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });
        getContentPane().add(j1);
        j1.setBounds(250, 280, 70, 30);

        j2.setBackground(new java.awt.Color(102, 102, 102));
        j2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        j2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });
        getContentPane().add(j2);
        j2.setBounds(330, 280, 70, 30);

        j3.setBackground(new java.awt.Color(102, 102, 102));
        j3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        j3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3);
        j3.setBounds(410, 280, 70, 30);

        tar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tar3ActionPerformed(evt);
            }
        });
        getContentPane().add(tar3);
        tar3.setBounds(430, 290, 10, 10);

        tar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarActionPerformed(evt);
            }
        });
        getContentPane().add(tar);
        tar.setBounds(270, 290, 20, 0);
        getContentPane().add(tar2);
        tar2.setBounds(350, 290, 40, 0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\Projek_bilik_pergerakan\\src\\waving-flag-of-is-a-region-of-malaysiar-vector-22515194.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, -30, 860, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String nama= namatxt.getText();
       String phone= notxt.getText(); 
       String alamat= alamattxt.getText(); 
       String tarikh= tar.getText();
       String tarikh2=tar2.getText();
       String tarikh3=tar3.getText();
       

       try { 
           try (FileWriter writer = new FileWriter("Data pelanggan", true)) {
               writer.write("....................................");
               writer.write(System.getProperty("line.separator"));
               writer.write("Nama : ");
               writer.write(nama);
               writer.write(System.getProperty("line.separator")); //untuk line baru supaya tidak bercampur dengan input yang pertama
               writer.write("Suhu Badan : ");
               writer.write(phone);
               writer.write(System.getProperty("line.separator"));
               writer.write("Nombor telepon : ");
               writer.write(alamat);
               writer.write(System.getProperty("line.separator"));
               writer.write("Tarikh : ");
               writer.write(tarikh+"/"+tarikh2+"/"+tarikh3);
               writer.write(System.getProperty("line.separator")); 
               writer.write("....................................");
               writer.write(System.getProperty("line.separator")); 
               writer.close();
               
           }
            JOptionPane.showMessageDialog(rootPane, "Berjaya");
           
       }catch (HeadlessException | IOException e){
           
           JOptionPane.showMessageDialog(rootPane,"Cuba Lagi");
       }








        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void namatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatxtActionPerformed

    private void tarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new admin().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         namatxt.setText("");
         notxt.setText("");
         alamattxt.setText("");
         
         
         
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            this.dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        String selectedValue = j1.getSelectedItem().toString();
        tar.setText(selectedValue);
        // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
            String selectedValue = j2.getSelectedItem().toString();
            tar2.setText(selectedValue);
        // TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
            String selectedValue = j3.getSelectedItem().toString();
            tar3.setText(selectedValue);
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void tar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamattxt;
    private javax.swing.JComboBox<String> j1;
    private javax.swing.JComboBox<String> j2;
    private javax.swing.JComboBox<String> j3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField notxt;
    private javax.swing.JTextField tar;
    private javax.swing.JTextField tar2;
    private javax.swing.JTextField tar3;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));

    }
}
